
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcp-admin
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "patch", "update"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-admin
  namespace: dev-ai
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcp-admin
subjects:
- kind: ServiceAccount
  name: mcp-admin
  namespace: dev-ai